<?php

namespace app\models;


use yii\db\ActiveRecord;

class Book extends ActiveRecord
{
    public static function tableName()
    {

        return 'Book';
       // TODO: Change the autogenerated stub
    }
    public function  getAuthor()
    {
        return $this->hasOne(Author::class, ['id'=> 'Author']);
    }
    public function rules()
    {
        return [
           [['Title', 'Author'], 'required']

        ];

} }