<?php

namespace app\models;


use yii\db\ActiveRecord;

class Svyaz extends ActiveRecord
{
    public static function tableName()
    {

        return 'Svyaz';
        // TODO: Change the autogenerated stub
    }
//    public function  getAuthor()
//    {
//     return $this->hasMany(Author::class, ['id'=> 'Author_id'])
//            ->viaTable('Book', ['id' => 'Book_id']);
//    }
    public function rules()
    {
        return [
            [['Author_id', 'Book_id'], 'required']

        ];

    } }